version: 2

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 10

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/rossigee/build-counter

  revive:
    min-confidence: 0.8

  govet:
    check-shadowing: true

  misspell:
    locale: US

  unused:
    check-exported: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    - path: main\.go
      linters:
        - gochecknoinits

  max-issues-per-linter: 0
  max-same-issues: 0