{{- if eq .Values.storage.mode "lightweight" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "build-counter.configMapName" . }}
  namespace: {{ include "build-counter.configMapNamespace" . }}
  labels:
    {{- include "build-counter.labels" . | nindent 4 }}
data: {}
{{- end }}